### ISSUE TITLE
How to use Agilent  .d folder formats in PbfGen and ProMex?

### ISSUE THREAD

**Issue by Arrow-V** [PNNL-Comp-Mass-Spec/Informed-Proteomics#13]
How to use Agilent  .d folder formats in PbfGen?I have installed ProteoWizard, and I tried to use msconvertGUI to convert the .d folder formats into .mzML files so that I can use it in PbfGen. However , when I use the previously created .pbf file in ProMex , it said Index out of range exception. How I can fix it?

**Comment by FarmGeek4Life** [comment]
Since you installed ProteoWizard, you might be able to directly use the .d folder with PbfGen. For fixing the Index out of range exception, I can't do anything without a stack trace - which should be part of the error output.

**Comment by Arrow-V** [comment]
```
F:\HSA>PbfGen.exe -s F:\HSA\HSA.d
Creating F:\HSA\HSA.pbf from F:\HSA\HSA.d
WARNING: Could not find a reader for file "F:\HSA\HSA.d". Is MSFileReader and/or ProteoWizard installed?
WARNING: Could not find a reader for file "F:\HSA\HSA.d". Is MSFileReader and/or ProteoWizard installed?
Exception while processing: Object reference not set to an instance of an object.
   at InformedProteomics.Backend.MassSpecData.PbfLcMsRun.BuildPbfFile(String specFileName, IMassSpecDataReader msdr, String pbfPath, String tempPath, IProgress`1 progress, Boolean keepDataReaderOpen, Int32 scanStart, Int32 scanEnd)
   at InformedProteomics.Backend.MassSpecData.PbfLcMsRun.GetPbfFile(String specFileName, IMassSpecDataReader msdr, String pbfFileName, IProgress`1 progress, Boolean keepDataReaderOpen, Int32 scanStart, Int32 scanEnd)
   at PbfGen.Program.Main(String[] args)

F:\HSA>
```

I try to directly use the .d folder with PbfGen, however it fails. I install the ProteoWizard by Windows 64-bit installer. And I have install the .NET 4.7.2

**Comment by FarmGeek4Life** [comment]
Where is ProteoWizard installed?

**Comment by Arrow-V** [comment]
It installed in F:\software\ProteoWizard   while the Informed-Proteomics installed in F:\Informed-Proteomics

**Comment by FarmGeek4Life** [comment]
So, if the path to msconvert.exe is `F:\software\ProteoWizard\msconvert.exe`, then please enter the command `set PATH=F:\software\ProteoWizard;%PATH%` before entering the command `PbfGen.exe -s F:\HSA\HSA.d`. (PbfGen does look for ProteoWizard in the default installation path for ProteoWizard, but you aren't using the default installation directory for ProteoWizard)

**Comment by Arrow-V** [comment]
Thank you very much! However, when I use ProMex to analyse the previously created .pbf file. It said "Exception while processing: Index was outside the bounds of the array." My data is in D:\20180714\20180714\                    Could you fix it?

C:\Users\Administrator\Documents>PbfGen.exe -s D:\20180714\20180714\C2.d
Creating D:\20180714\20180714\C2.pbf from D:\20180714\20180714\C2.d
Searching for ProteoWizard files...
Using vendor Centroiding
Writing metadata, 100.0% complete
PbfFormatVersion: 150608

C:\Users\Administrator\Documents>ProMex.exe -i D:\20180714\20180714\C2.pbf -minCharge 2 -maxCharge 60 -minMass 3000 -maxMass 50000 -score n -csv n -maxThreads 0
************ ProMex version 1.0.6510 (October 28, 2017) ************
InputPath    D:\20180714\20180714\C2.pbf
OutputPath
MinMass      3000
MaxMass      50000
MinCharge    2
MaxCharge    60
FeatureMap   True
ScoreReport  False
LikelihoodRatioThreshold -10
MaxThreads   2
Start loading MS1 data from D:\20180714\20180714\C2.pbf
Caching peaks in MS1 spectra: 178 scans
Sorting MS1 peaks: 72,231 peaks
Complete loading MS1 data. Elapsed Time = 0.351 sec
Start MS1 feature extraction.
Processing 0.8% of mass bins (3062.6 Da); elapsed time = 3.524 sec; # of features = 0
Processing 1.5% of mass bins (3125.1 Da); elapsed time = 4.041 sec; # of features = 0
Processing 2.3% of mass bins (3187.6 Da); elapsed time = 4.482 sec; # of features = 0
Processing 3.0% of mass bins (3250.1 Da); elapsed time = 4.971 sec; # of features = 0
Processing 3.8% of mass bins (3312.6 Da); elapsed time = 5.475 sec; # of features = 0
Processing 4.5% of mass bins (3375.1 Da); elapsed time = 5.983 sec; # of features = 0
Processing 5.3% of mass bins (3437.6 Da); elapsed time = 6.498 sec; # of features = 0
Processing 6.0% of mass bins (3500.1 Da); elapsed time = 7.010 sec; # of features = 0
Processing 6.8% of mass bins (3562.6 Da); elapsed time = 7.510 sec; # of features = 0
Processing 7.5% of mass bins (3625.1 Da); elapsed time = 8.035 sec; # of features = 0
Processing 8.3% of mass bins (3687.6 Da); elapsed time = 8.585 sec; # of features = 0
Processing 9.0% of mass bins (3750.1 Da); elapsed time = 9.142 sec; # of features = 0
Processing 9.8% of mass bins (3812.6 Da); elapsed time = 9.695 sec; # of features = 0
Processing 10.5% of mass bins (3875.1 Da); elapsed time = 10.269 sec; # of features = 0
Processing 11.3% of mass bins (3937.6 Da); elapsed time = 10.833 sec; # of features = 0
Processing 12.0% of mass bins (4000.1 Da); elapsed time = 11.393 sec; # of features = 0
Processing 12.8% of mass bins (4062.6 Da); elapsed time = 11.948 sec; # of features = 0
Processing 13.5% of mass bins (4154.1 Da); elapsed time = 12.517 sec; # of features = 0
Processing 14.3% of mass bins (4279.1 Da); elapsed time = 13.109 sec; # of features = 0
Processing 15.0% of mass bins (4404.1 Da); elapsed time = 13.713 sec; # of features = 0
Processing 15.8% of mass bins (4529.1 Da); elapsed time = 14.357 sec; # of features = 0
Processing 16.5% of mass bins (4654.1 Da); elapsed time = 15.013 sec; # of features = 0
Processing 17.3% of mass bins (4779.1 Da); elapsed time = 15.659 sec; # of features = 0
Processing 18.0% of mass bins (4904.1 Da); elapsed time = 16.360 sec; # of features = 0
Processing 18.8% of mass bins (5029.1 Da); elapsed time = 17.072 sec; # of features = 0
Processing 19.5% of mass bins (5154.1 Da); elapsed time = 17.787 sec; # of features = 0
Processing 20.3% of mass bins (5279.1 Da); elapsed time = 18.526 sec; # of features = 0
Processing 21.0% of mass bins (5404.1 Da); elapsed time = 19.277 sec; # of features = 0
Processing 21.8% of mass bins (5529.1 Da); elapsed time = 20.025 sec; # of features = 0
Processing 22.5% of mass bins (5654.1 Da); elapsed time = 20.814 sec; # of features = 0
Processing 23.3% of mass bins (5779.1 Da); elapsed time = 21.644 sec; # of features = 0
Processing 24.0% of mass bins (5904.1 Da); elapsed time = 22.461 sec; # of features = 0
Processing 24.8% of mass bins (6029.1 Da); elapsed time = 23.274 sec; # of features = 0
Processing 25.5% of mass bins (6154.1 Da); elapsed time = 24.097 sec; # of features = 0
Processing 26.3% of mass bins (6279.1 Da); elapsed time = 24.921 sec; # of features = 0
Processing 27.1% of mass bins (6404.1 Da); elapsed time = 25.791 sec; # of features = 0
Processing 27.8% of mass bins (6529.1 Da); elapsed time = 26.648 sec; # of features = 0
Processing 28.6% of mass bins (6654.1 Da); elapsed time = 27.506 sec; # of features = 0
Processing 29.3% of mass bins (6779.1 Da); elapsed time = 28.459 sec; # of features = 0
Processing 30.1% of mass bins (6904.1 Da); elapsed time = 29.390 sec; # of features = 0
Processing 30.8% of mass bins (7029.1 Da); elapsed time = 30.314 sec; # of features = 0
Processing 31.6% of mass bins (7154.1 Da); elapsed time = 31.234 sec; # of features = 0
Processing 32.3% of mass bins (7279.1 Da); elapsed time = 32.236 sec; # of features = 0
Processing 33.1% of mass bins (7404.1 Da); elapsed time = 33.194 sec; # of features = 0
Processing 33.8% of mass bins (7529.1 Da); elapsed time = 34.166 sec; # of features = 0
Processing 34.6% of mass bins (7654.1 Da); elapsed time = 35.153 sec; # of features = 0
Processing 35.3% of mass bins (7779.1 Da); elapsed time = 36.191 sec; # of features = 0
Processing 36.1% of mass bins (7904.1 Da); elapsed time = 37.239 sec; # of features = 0
Processing 36.8% of mass bins (8029.1 Da); elapsed time = 38.260 sec; # of features = 0
Processing 37.6% of mass bins (8154.1 Da); elapsed time = 39.280 sec; # of features = 0
Processing 38.3% of mass bins (8366.3 Da); elapsed time = 40.334 sec; # of features = 0
Processing 39.1% of mass bins (8616.3 Da); elapsed time = 41.487 sec; # of features = 0
Processing 39.8% of mass bins (8866.3 Da); elapsed time = 42.641 sec; # of features = 0
Processing 40.6% of mass bins (9116.3 Da); elapsed time = 43.854 sec; # of features = 0
Processing 41.3% of mass bins (9366.3 Da); elapsed time = 45.275 sec; # of features = 0
Processing 42.1% of mass bins (9616.3 Da); elapsed time = 46.661 sec; # of features = 0
Processing 42.8% of mass bins (9866.3 Da); elapsed time = 48.022 sec; # of features = 0
Processing 43.6% of mass bins (10116.3 Da); elapsed time = 49.396 sec; # of features = 0
Processing 44.3% of mass bins (10366.3 Da); elapsed time = 50.732 sec; # of features = 0
Processing 45.1% of mass bins (10616.3 Da); elapsed time = 52.136 sec; # of features = 0
Processing 45.8% of mass bins (10866.3 Da); elapsed time = 53.545 sec; # of features = 0
Processing 46.6% of mass bins (11116.3 Da); elapsed time = 55.064 sec; # of features = 0
Processing 47.3% of mass bins (11366.3 Da); elapsed time = 56.548 sec; # of features = 0
Processing 48.1% of mass bins (11616.3 Da); elapsed time = 58.118 sec; # of features = 0
Processing 48.8% of mass bins (11866.3 Da); elapsed time = 59.933 sec; # of features = 0
Processing 49.6% of mass bins (12116.3 Da); elapsed time = 62.134 sec; # of features = 0
Processing 50.3% of mass bins (12366.3 Da); elapsed time = 64.000 sec; # of features = 0
Processing 51.1% of mass bins (12616.3 Da); elapsed time = 65.669 sec; # of features = 0
Processing 51.9% of mass bins (12866.3 Da); elapsed time = 67.442 sec; # of features = 0
Processing 52.6% of mass bins (13116.3 Da); elapsed time = 69.263 sec; # of features = 0
Processing 53.4% of mass bins (13366.3 Da); elapsed time = 71.121 sec; # of features = 0
Processing 54.1% of mass bins (13616.3 Da); elapsed time = 72.990 sec; # of features = 0
Processing 54.9% of mass bins (13866.3 Da); elapsed time = 74.973 sec; # of features = 0
Processing 55.6% of mass bins (14116.3 Da); elapsed time = 76.891 sec; # of features = 0
Processing 56.4% of mass bins (14366.3 Da); elapsed time = 78.726 sec; # of features = 0
Processing 57.1% of mass bins (14616.3 Da); elapsed time = 80.757 sec; # of features = 0
Processing 57.9% of mass bins (14866.3 Da); elapsed time = 82.782 sec; # of features = 0
Processing 58.6% of mass bins (15116.3 Da); elapsed time = 84.709 sec; # of features = 0
Processing 59.4% of mass bins (15366.3 Da); elapsed time = 86.659 sec; # of features = 0
Processing 60.1% of mass bins (15616.3 Da); elapsed time = 88.625 sec; # of features = 0
Processing 60.9% of mass bins (15866.3 Da); elapsed time = 90.587 sec; # of features = 0
Processing 61.6% of mass bins (16116.3 Da); elapsed time = 92.578 sec; # of features = 0
Processing 62.4% of mass bins (16366.3 Da); elapsed time = 94.566 sec; # of features = 0
Processing 63.1% of mass bins (16848.5 Da); elapsed time = 96.725 sec; # of features = 0
Processing 63.9% of mass bins (17348.5 Da); elapsed time = 98.932 sec; # of features = 0
Processing 64.6% of mass bins (17848.5 Da); elapsed time = 101.169 sec; # of features = 0
Processing 65.4% of mass bins (18348.5 Da); elapsed time = 103.443 sec; # of features = 0
Processing 66.1% of mass bins (18848.5 Da); elapsed time = 105.767 sec; # of features = 0
Processing 66.9% of mass bins (19348.5 Da); elapsed time = 108.140 sec; # of features = 0
Processing 67.6% of mass bins (19848.5 Da); elapsed time = 110.539 sec; # of features = 0
Processing 68.4% of mass bins (20348.5 Da); elapsed time = 112.945 sec; # of features = 0
Processing 69.1% of mass bins (20848.5 Da); elapsed time = 115.384 sec; # of features = 0
Processing 69.9% of mass bins (21348.5 Da); elapsed time = 117.748 sec; # of features = 0
Processing 70.6% of mass bins (21848.5 Da); elapsed time = 120.121 sec; # of features = 0
Processing 71.4% of mass bins (22348.5 Da); elapsed time = 122.507 sec; # of features = 0
Processing 72.1% of mass bins (22848.5 Da); elapsed time = 125.335 sec; # of features = 0
Processing 72.9% of mass bins (23348.5 Da); elapsed time = 127.770 sec; # of features = 0
Processing 73.6% of mass bins (23848.5 Da); elapsed time = 130.114 sec; # of features = 0
Processing 74.4% of mass bins (24348.5 Da); elapsed time = 132.487 sec; # of features = 0
Processing 75.1% of mass bins (24848.5 Da); elapsed time = 134.877 sec; # of features = 0
Processing 75.9% of mass bins (25348.5 Da); elapsed time = 137.243 sec; # of features = 0
Processing 76.6% of mass bins (25848.5 Da); elapsed time = 139.818 sec; # of features = 0
Processing 77.4% of mass bins (26348.5 Da); elapsed time = 142.313 sec; # of features = 0
Processing 78.2% of mass bins (26848.5 Da); elapsed time = 144.749 sec; # of features = 0
Processing 78.9% of mass bins (27348.5 Da); elapsed time = 147.610 sec; # of features = 0
Processing 79.7% of mass bins (27848.5 Da); elapsed time = 150.463 sec; # of features = 0
Processing 80.4% of mass bins (28348.5 Da); elapsed time = 153.339 sec; # of features = 0
Processing 81.2% of mass bins (28848.5 Da); elapsed time = 156.227 sec; # of features = 0
Processing 81.9% of mass bins (29348.5 Da); elapsed time = 159.328 sec; # of features = 0
Processing 82.7% of mass bins (29848.5 Da); elapsed time = 161.826 sec; # of features = 0
Processing 83.4% of mass bins (30348.5 Da); elapsed time = 164.218 sec; # of features = 0
Processing 84.2% of mass bins (30848.5 Da); elapsed time = 166.598 sec; # of features = 0
Processing 84.9% of mass bins (31348.5 Da); elapsed time = 168.946 sec; # of features = 0
Processing 85.7% of mass bins (31848.5 Da); elapsed time = 171.327 sec; # of features = 0
Processing 86.4% of mass bins (32348.5 Da); elapsed time = 173.668 sec; # of features = 0
Processing 87.2% of mass bins (32929.0 Da); elapsed time = 176.114 sec; # of features = 0
Processing 87.9% of mass bins (33929.0 Da); elapsed time = 178.771 sec; # of features = 0
Processing 88.7% of mass bins (34929.0 Da); elapsed time = 181.410 sec; # of features = 0
Processing 89.4% of mass bins (35929.0 Da); elapsed time = 184.082 sec; # of features = 0
Processing 90.2% of mass bins (36929.0 Da); elapsed time = 186.774 sec; # of features = 0
Processing 90.9% of mass bins (37929.0 Da); elapsed time = 189.505 sec; # of features = 0
Processing 91.7% of mass bins (38929.0 Da); elapsed time = 192.247 sec; # of features = 0
Processing 92.4% of mass bins (39929.0 Da); elapsed time = 195.002 sec; # of features = 0
Processing 93.2% of mass bins (40929.0 Da); elapsed time = 197.794 sec; # of features = 0
Processing 93.9% of mass bins (41929.0 Da); elapsed time = 200.552 sec; # of features = 0
Processing 94.7% of mass bins (42929.0 Da); elapsed time = 203.341 sec; # of features = 0
Processing 95.4% of mass bins (43929.0 Da); elapsed time = 206.141 sec; # of features = 0
Processing 96.2% of mass bins (44929.0 Da); elapsed time = 208.989 sec; # of features = 0
Processing 96.9% of mass bins (45929.0 Da); elapsed time = 211.811 sec; # of features = 0
Processing 97.7% of mass bins (46929.0 Da); elapsed time = 214.695 sec; # of features = 0
Processing 98.4% of mass bins (47929.0 Da); elapsed time = 217.637 sec; # of features = 0
Processing 99.2% of mass bins (48929.0 Da); elapsed time = 220.561 sec; # of features = 0
Processing 99.9% of mass bins (49929.0 Da); elapsed time = 223.530 sec; # of features = 0
Complete MS1 feature extraction.
 - Elapsed time = 223.747 sec
 - Number of extracted features = 0
Start selecting mutually independent features from feature network graph
Complete feature filtration
 - Elapsed time = 0.032 sec
 - Number of filtered features = 0
 - ProMex output: D:\20180714\20180714\C2.ms1ft
Exception while processing: Index was outside the bounds of the array.
   at InformedProteomics.FeatureFinding.Graphics.LcMsFeatureMap.GetColorBreaksTable(Int32 nColors, IEnumerable`1 features)
   at InformedProteomics.FeatureFinding.Graphics.LcMsFeatureMap.SaveImage(String imgPath, Int32 nColors)
   at InformedProteomics.FeatureFinding.LcMsFeatureFinderLauncher.CreateFeatureMapImage(LcMsRun run, String featuresFilePath, String imgFilePath)
   at InformedProteomics.FeatureFinding.LcMsFeatureFinderLauncher.ProcessFile(String rawFile)
   at InformedProteomics.FeatureFinding.LcMsFeatureFinderLauncher.Run()
   at ProMex.Program.Main(String[] args)

**Comment by FarmGeek4Life** [comment]
The issue in this case is that for some reason, no features were found. I don't know why there were no features found at all, and it might be a bug in handling the differences between Thermo .raw data and Agilent or Bruker .d data. To figure out the exact issue, we would probably need a copy of the input dataset.

**Comment by Arrow-V** [comment]
could you give me a email？ I send my data to you

**Comment by FarmGeek4Life** [comment]
How big are the files? If they are bigger than 20MB, it is much easier to use something like dropbox, google drive, or onedrive to share them, than it is to email them.

**Comment by Arrow-V** [comment]
just 8MB

**Comment by FarmGeek4Life** [comment]
if you zip the .d folder, you should be able to attach it to this GitHub issue (it has a 25MB limit)

**Comment by Arrow-V** [comment]
[data.zip](https://github.com/PNNL-Comp-Mass-Spec/Informed-Proteomics/files/2305086/data.zip)
ok

**Comment by Jungkap** [comment]
There could be several issues to use ProMex for Agilent (Q)TOF instrument
data.

The proteins you are looking for should be isotopically resolved with your
Agilent instrument. If the mass is over 20 kDa, typical Agilent (Q)TOF
instruments would not able to resolve isotopomer envelops of proteins you
are looking for. For example, if you are analyzing mAb samples with Agilent
instrument, ProMex and MSPathFinder is not the right software. In such
case, you may need to Agilent's software like BioConfirm.

Jungkap

**Comment by Arrow-V** [comment]
@FarmGeek4Life  Emmmm .Could you fix the problem? I am really like this software and I hope it can work.
