### ISSUE TITLE
Crash if NumMods >= 28

### ISSUE THREAD

**Issue by liv-acollins** [PNNL-Comp-Mass-Spec/Informed-Proteomics#4]
Input:
NumMods=28
HO3P,STY,opt,any,Phospho # Phosphorylation
O1,M,opt,any,Oxidation     # Oxidation M
C12H20O10,RK,opt,any,Hex(2)     # Lactostylation
C2H2O,K,opt,Prot-N-term,Acetyl     # Acetylation Protein N-term (C2H2O can be replaced with "H(2) C(2) O")

On execute:

Exception parsing the file for parameter -mod: The given key was not present in the dictionary.
Exception while processing: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at InformedProteomics.Backend.Data.Sequence.ModificationParams.GenerateModCombMap()
   at InformedProteomics.Backend.Data.Sequence.AminoAcidSet..ctor(IEnumerable`1 searchModifications, Int32 maxNumModsPerSequence)
   at MSPathFinderT.TopDownInputParameters.LoadModsFile(String modFilePath)
   at MSPathFinderT.TopDownInputParameters.Parse(Dictionary`2 parameters)
   at MSPathFinderT.Program.Main(String[] args)

**Comment by FarmGeek4Life** [comment]
I can duplicate this issue, but I still haven't found the exact cause of the problem (beyond the high maximum number of modifications)
